name: "tailcalls"
version: "0.1.2"
author: "Michael Bürgerling <michael.buergerling@gmail.com>"
description: "A library for trampolining tail calls by hand in cases when tail call optimization isn't done automatically. This library is ported from Scala's standard library (TailRec)."
homepage: "https://github.com/welopment/tailcalls"
environment:
  sdk: '>=1.8.0 <3.0.0'


dependencies:


dev_dependencies:
  test: '1.6.3' 
  pedantic: ^1.0.0
